require("player_profile.patches.SelectViewConfig")
require("player_profile.patches.SelectView")
require("player_profile.patches.ResultView")
require("player_profile.patches.GameplayController")
require("player_profile.patches.GameController")
